Added Internet Requirement For Getting Started.
pyscript/pyscript pull request #549
Opened 2022-06-24 09:38 UTC by Tosin-JD

I updated the getting started to show help beginners ensure that they have a constant internet connection to access dependencies like [pyodide] (https://pyodide.org/en/stable/index.html) that are hosted online.

2022-06-24 17:35 UTC, fpliger requested changes

2022-07-04 18:23 UTC, marimeireles commented on docs/tutorials/getting-started.md
> +You will also need constant internet connection to access the other packages which are hosted online that pyscript depend on.
Yes, I agree.
We should make it clear how to run it offline.
Stable internet connection is such a problem in so many places in the world.
This is an impactful way =) to increase our reach.
If @Tosin-JD doesn't want to tackle it for now I'll add it to the issue I'm writing on what we should document.

2022-07-04 20:23 UTC, Tosin-JD commented on docs/tutorials/getting-started.md
> +You will also need constant internet connection to access the other packages which are hosted online that pyscript depend on.
> @Tosin-JD  Thanks! This is a good observation... but I'm afraid it's limiting. You can actually have a dev environment running without connectivity. Maybe it's probably best to guide the users on how to create a local setup that doesn't require connectivity on the installation section?

I think it is good to specify how to run pyscript completely offline in the documentation. But will it be best to include it in the getting started section for beginners? I will like to contribute to making it completely offline. But it requires the download and installation of the dependent module pyodide.

2022-11-14 18:15 UTC, tedpatrick commented
Thank you for your PR contribution to PyScript. We are closing PRs older than 90 days with limited activity.

2022-11-14 18:15 UTC, closed without merging