update makefile with all instruction
pyscript/pyscript pull request #603
Opened 2022-07-14 06:09 UTC by anirrudh

This change addresses #585 - the assumptions are made as follows:

* A conda environment is activated, either created from the environment.yml file or from the Makefile using the setup instruction.
* localhost:8080/examples/ is the default endpoint

I'm also working on an isolated Dockerfile in parallel. Please let me know if this is enough, or If we need to add the ability to create the conda environment from within the `all` instruction as well.

Cc: @marimeireles

2022-07-29 00:57 UTC, marimeireles commented
Hey @anirrudh!
Thanks for picking this up! ✨
Sorry I opened this issue but I remember I was having a discussion with @fpliger so, do you want a conda environment to be created too? Do you remember what you had in mind?
Also I wonder if `make all` is a good name... Maybe `make install example`? I don't know.
But thanks again for the contribution! =)

2022-08-04 20:44 UTC, fpliger commented on pyscriptjs/Makefile
> +	npm run build
I think this can be removed since dev will also build (and then watch)

2022-08-04 20:45 UTC, fpliger commented on pyscriptjs/Makefile
> +	npm run dev
I think it's better to change to `make dev` just in case we change cmds in the future...

2022-08-04 20:48 UTC, fpliger requested changes
Great, thanks for the contribution @anirrudh ! I left some minor comments but I think the main think for address before merging is the name of the cmd, as @marimeireles pointed out.

Maybe `run-examples`?

2022-08-25 20:44 UTC, marimeireles commented
Due to inactivity and #689 being merged, closing this one.
Sorry for the long time to review it @anirrudh, thank you very much for the time here!

2022-08-25 20:44 UTC, closed without merging