Update CONTRIBUTING.md
pyscript/pyscript pull request #728
Opened 2022-08-26 15:56 UTC by marimeireles

Adding docs on how to make a pr

2022-08-27 00:04 UTC, fpliger requested changes
minor changes but would be good to the these in :)

2022-08-27 00:04 UTC, fpliger commented on CONTRIBUTING.md
> +We recommend you to create a new local branch and develop your changes in this brance=h. You can do that by using:
typo brance=h -> branch

2022-08-27 00:04 UTC, fpliger commented on CONTRIBUTING.md
> +The changes should try to be kept within the scope of the issue, or within a well defined scope that should be clearly explained on the PR title. If you can't think of a title that explains your PR w
Think this sentence could be rephrased to make it more readable. Something like "Please try to keep the changes on your PR within the scope of the issue,..."

2022-08-27 00:04 UTC, fpliger commented on CONTRIBUTING.md
> +The changes should try to be kept within the scope of the issue, or within a well defined scope that should be clearly explained on the PR title. If you can't think of a title that explains your PR w
Also, you could add a `'` between "your PR" and "well"

2022-08-29 18:10 UTC, marimeireles commented
Thanks for the input @fpliger. Changed :)

2022-08-29 18:34 UTC, fpliger approved these changes
lgtm! TY @marimeireles !

2022-09-06 21:35 UTC, merged