mario enhancements
pyscript/pyscript pull request #742
Opened 2022-08-31 14:54 UTC by meg-1

_**adding a few enhancements to the Mario example for better UI and use.**_
- fixing a bug where a snippet of code accidentally displayed on the main page
- fixing the PyScript code and tag indentation
- adding styles for the simple instructions to be visible

2022-09-08 13:25 UTC, marimeireles requested changes
Besides this little nitpick... For some reason the box where the video should be showing up is just a blue box on my screen.
So I think that's broken?
Maybe because of some indentation issue.

2022-09-08 13:31 UTC, marimeireles commented
This is such a complicated example though.
I'd really like to move it from here to the collective.
Also, I'm available for a quick check up on the status of the collective, like 30min. Maybe we should do that some point next week? There are a lot of lose ends I think it'd be better discussed live rather than through text.
Thoughts @fpliger, @pauleveritt?

2022-09-08 13:32 UTC, marimeireles commented
Oh, and thank you for tackling this @meg-1! :)
Let's see what's the future of this example, it's a complex one and we're thinking about just having the simpler ones in this repo, but anyways it'd be nice to have them with a better presentation.
Thanks and cheers.

2022-09-11 13:27 UTC, pauleveritt commented
Hi @meg-1 thanks for putting work in on this. As @marimeireles we're working to get something off the ground in the "Collective". It will mean some refactoring and some test writing. If you're up for it, we can work together and help define some of the standards.

2022-09-21 14:39 UTC, meg-1 commented on examples/mario/play_mario.html
> +    <link rel="stylesheet" href="css/game.css" />
thank you for your feedback! just rolled back the changes on the two lines as requested :)

2022-09-21 14:44 UTC, meg-1 commented
> Oh, and thank you for tackling this @meg-1! :) Let's see what's the future of this example, it's a complex one and we're thinking about just having the simpler ones in this repo, but anyways it'd be nice to have them with a better presentation. Thanks and cheers.

thank you so much for your answers!! apologies for responding so late :') and of course, I understand! sounds like a sound decision. only glad to help out as much as i can :)

2022-09-21 14:48 UTC, meg-1 commented
> Hi @meg-1 thanks for putting work in on this. As @marimeireles we're working to get something off the ground in the "Collective". It will mean some refactoring and some test writing. If you're up for it, we can work together and help define some of the standards.

hi, @pauleveritt ! sorry for such a late reply :') but thank you for answer! seems like quite the proposition! i'm down for whatever i can help to tackle in the development of the repository :)

2022-10-06 11:25 UTC, tedpatrick commented
Contributed examples should be submitted as PRs to https://github.com/pyscript/pyscript-collective. We are focusing the examples within [PyScript](https://github.com/pyscript/pyscript) on feature use cases and testing.

Thanks for your patience, understanding, and contribution.

2022-10-06 11:25 UTC, closed without merging