Format the TypeScript files
pyscript/pyscript pull request #877
Opened 2022-10-21 15:37 UTC by woxtu

Hi,

This PR just ran Prettier to format the TypeScript files.

2022-10-22 23:00 UTC, antocuni requested changes
**Please don't merge** :)

I don't have anything against this PR, and thank you for submitting it.
But I'm doing a very heavy refactoring in #881 and this PR will cause a lot of conflicts.
It makes more sense to wait for it to land and then re-run the code formatter on the new code, probably.

2022-10-27 14:46 UTC, madhur-tandon commented
@woxtu could you rebase on `main` and then run the formatter again?

2022-10-28 02:31 UTC, woxtu commented
Sure.

2022-10-28 08:41 UTC, madhur-tandon approved these changes

2022-10-28 08:43 UTC, antocuni approved these changes

2022-10-28 08:48 UTC, merged